name: Publish Docker Image
on: 
  push:
    branches:
      - 'dev'
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      -
        name: Job Start
        uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#dev'
          message: Starting gr3ysh3ll dev build and push...
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fonalex45/gr3ysh3ll:dev
      -
        name: Notify Slack Channel of finished build
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#dev'
          message: Build Complete
        if: always()
